version: '3.9'
services:
  db:
    image: postgres:13
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    restart: always
    volumes:
      - data:/var/lib/postgresql
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: osttra

  webservice:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_CONN: postgresql://user:password123@db:5432/osttra?sslmode=require

volumes:
  data: